name: my_glide
description: Cross platform (iOS / android) app voor start admin, en meer.......

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.3.0+3107

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # interface with the web services
  http: ^0.12.0

  # encrypten / descrypten of a string to store password
  encrypt: ^1.0.0

  # icons for ios and android
  # regenerate icons with the statement "flutter pub pub run flutter_laucher_icons:main"
  flutter_launcher_icons: ^0.7.0

  # check internet connection
  connectivity: ^0.3.2

  # store data locally on device
  shared_preferences: ^0.5.3+4

  # menu per record
  flutter_slidable: "^0.4.9"

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # add number inputwheel
  numberpicker: ^0.1.7

  #Date picker
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git

  # Intenationalization and localization like date formating
  intl: ^0.15.7

  # Url launcher to open email, cellphone or sms etc.
  url_launcher: ^4.0.3

  #Mailer with HTML support
  flutter_mailer: ^0.4.0

  #GPS locatie
  geolocator: '^3.0.1'

  #Shrink text
  auto_size_text: ^2.0.2+1

  # avatars worden in cache gezet
  cached_network_image: ^1.1.1

  # toon HTML pagina
  flutter_html: ^0.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  image_path: assets/images/silzweeficon.png
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/gezc_logo_transp.png
  - assets/images/gezc_geel-blauw.png
  - assets/images/demo_marker.png
  - assets/images/no_avatar.png
  - assets/images/communicatie.png
  - assets/images/whatsapp.png
  - assets/images/chute.png
  - assets/images/rotate_to_portrait.png

  - assets/incident formulier.html
  
  - assets/demo/Aanwezig/LedenAanwezigJSON.json

  - assets/demo/Types/TypesJSON_4.json

  - assets/demo/Login/getUserInfoJSON.json

  - assets/demo/Startlijst/LogboekJSON.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10063.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10213.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10265.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10395.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10408.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10632.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10804.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10855.json
  - assets/demo/Startlijst/StartlijstVandaagJSON_10858.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10063.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10213.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10265.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10395.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10408.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10632.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10804.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10855.json
  - assets/demo/Startlijst/VliegerRecencyJSON_10858.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_200.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_223.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_224.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_226.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_252.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_255.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_295.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_296.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_297.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_402.json
  - assets/demo/Startlijst/VliegtuigLogboekJSON_604.json

  - assets/demo/Vliegtuigen/GetClubkistenJSON.json
  - assets/demo/Vliegtuigen/GetVliegtuigenJSON.json

  - assets/demo/Leden/LedenJSON.json

  - assets/demo/Leden/avatars/truus_de_mier.jpg
  - assets/demo/Leden/avatars/bor_de_wolf.png
  - assets/demo/Leden/avatars/meneer_de_uil.jpg
  - assets/demo/Leden/avatars/zoef_de_haas.png
  - assets/demo/Leden/avatars/juffrouw_ooievaar.jpg
  - assets/demo/Leden/avatars/lowieke_de_vos.png
  - assets/demo/Leden/avatars/momfer_de_mol.png
  - assets/demo/Leden/avatars/gerrit_de_postduif.png
  - assets/demo/Leden/avatars/isadora_paradijsvogel.png
  - assets/demo/Leden/avatars/meindert_het_paard.jpg
  - assets/demo/Leden/avatars/willem.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
